export const ACTIONS = {

  // App
  APP_USER: 'APP_USER',
  APP_LOADING: 'APP_LOADING',
  APP_ERROR: 'APP_ERROR',

  // Cooks
  COOKS_RESET: 'COOKS_RESET',

  // Fruits
  FRUITS_RESET: 'FRUITS_RESET',

  // Recipes
  RECIPES_RESET: 'RECIPES_RESET',

  // Juices
  JUICES_RESET: 'JUICES_RESET',
  JUICES_ADD: 'JUICES_ADD',
};
